name: Build ReactJS Application

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js and Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '16' # Ensure compatibility with React
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Upload build directory as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  docker_build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          tags: chess-game:1.0

      - name: List Docker Images
        run: docker images
