name: build the reacjs application 

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: install reactjs 
              uses: actions/setup-node@v4
              with:
                node-version: '14'
                cache: 'npm'

            - name: Install dependencies
              run: npm install
        
            - name: Build the app
              run: npm run build
            - name: upload the artifacts
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: dist/*