name: build the reacjs application 

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: install reactjs 
              uses: actions/setup-node@v4
              with:
                node-version: '12'
                cache: 'npm'

            - name: Install dependencies
              run: npm install
        
            - name: Build the app
              run: npm run build
    docker_build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build the image
              uses: docker/build-push-action@v6
              with:
                push: false
                context: .
                tags: chess-game:1.0 
            - run: docker images